// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_test_task/test/api_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_test_task/models/comments_list_model.dart' as _i6;
import 'package:flutter_test_task/models/post_list_model.dart' as _i5;
import 'package:flutter_test_task/util/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.PostListModel>> fetchPosts() => (super.noSuchMethod(
        Invocation.method(
          #fetchPosts,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.PostListModel>>.value(<_i5.PostListModel>[]),
      ) as _i4.Future<List<_i5.PostListModel>>);

  @override
  _i4.Future<List<_i6.CommentsListModel>> fetchComments(String? fetchType) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchComments,
          [fetchType],
        ),
        returnValue: _i4.Future<List<_i6.CommentsListModel>>.value(
            <_i6.CommentsListModel>[]),
      ) as _i4.Future<List<_i6.CommentsListModel>>);

  @override
  _i4.Future<Map<String, dynamic>> addPost(
    String? userId,
    String? title,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPost,
          [
            userId,
            title,
            body,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> editPost(
    String? id,
    String? userId,
    String? title,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPost,
          [
            id,
            userId,
            title,
            body,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> deletePost(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [id],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #deletePost,
            [id],
          ),
        )),
      ) as _i4.Future<String>);
}
